kjappelbaum/pyepal

- README.md
- docs/index.rst
> docs: link to chemrxiv, closes #66

- README.md
> docs: cleanup README; add link to chemrxiv

- .lgtm.yml
- README.md
- added badge to README
- added configuration file
- check upon PR is activated using the GitHub app
> chore: lgtm integration

- .lgtm.yml
> chore: updated lgtm config

- pyepal/__init__.py
- pyepal/models/coregionalized.py
- pyepal/models/gbdt.py
- pyepal/models/gpr.py
- pyepal/pal/core.py
- pyepal/pal/pal_base.py
- pyepal/pal/pal_coregionalized.py
- pyepal/pal/pal_gbdt.py
- pyepal/pal/pal_gpy.py
- pyepal/pal/pal_sklearn.py
- pyepal/pal/schedules.py
- pyepal/pal/utils.py
- pyepal/pal/validate_inputs.py
This will make wildcard imports a bit more well-defined, especially if the code base grows.
Also makes the `get_kernel` functions for GPy public.
> chore: define __all__

- docs/requirements.txt
> fix: add missing dependencies for docs

- .github/workflows/pre_commit.yml
- .github/workflows/python_package.yml
- .pre-commit-config.yaml
- .pylintrc
- pyepal/pal/_hypervolume.py
- requirements.txt
- setup.py
> chore: Fix precommit

- setup.py
> fix: only install pyepal package

- requirements.txt
- setup.py
> chore: pin only major version for most dependencies

- .github/workflows/python_package.yml
- README.md
- docs/getting_started.rst
- tests/test_pal_sklearn.py
> chore: adding macos to github actions

- setup.py
> fix: also include subpackages

- tests/test_pal_sklearn.py
> chore: fix the random seed for the sklearn models

- pyepal/pal/core.py
- pyepal/pal/pal_base.py
- tests/test_pal_core.py
This PR adds the following sampling options:
- sample also from discarded points
- mean/median/Euclidean aggregation for the uncertainties
> feat: added new sampling options

- pyepal/models/gpr.py
Can be used to make the models for the interaction between the outputs more fancy (but also more tricky to fit).
> feat: allow to change the rank of the ICM models

- pyepal/pal/pal_base.py
> chore: exposing sampling options in run_one_step

- tests/test_pal_sklearn.py
> chore: fixing random seed in sklearn tests

- pyepal/models/nt.py
- pyepal/pal/pal_neural_tangent.py
> fix: closes #153

- setup.py
> fix: add description

- pyepal/pal/pal_finite_ensemble.py
> fix: jax not imported on top level

- pyepal/pal/core.py
- pyepal/pal/pal_base.py
for compatibility with the original implementation.
> feat: adding option to sample without dimensionless uncertainties

- pyepal/pal/pal_base.py
> feat: Replace by measurement

- pyepal/pal/utils.py
- tests/test_pal_utils.py
can be used instead of HV error, less ambiguuos.
> feat: added new non-dimensional metric 

- MANIFEST.in
> fix: including requirements.txt in manifest

- CITATION.cff
> chore: add `CITATION.cff`

- README.md
- pyepal/pal/pal_base.py
- pyepal/pal/pal_coregionalized.py
- pyepal/pal/pal_finite_ensemble.py
- pyepal/pal/pal_gbdt.py
- pyepal/pal/pal_gpflowgpr.py
- pyepal/pal/pal_gpy.py
- pyepal/pal/pal_neural_tangent.py
- pyepal/pal/pal_sklearn.py
- pyepal/pal/validate_inputs.py
- pyepal/plotting/__init__.py
- requirements.txt
- setup.py
- tests/test_pal_base.py
- tests/test_plotting.py
- tests/test_validate_inputs.py
Officially it is an breaking change as it changes the behavior of `means` and now asks users to use part of the private API to implement a new `PAL` object. However, given #185 this seems the better solution. 
Still need to add a test that covers the problem described in #185 and maybe we should then also move `std` into the private namespace.
> feat: introduce `means` property
